name: Generate test coverage report.
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Test
        run: npm run test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
